### PR TITLE
Fallback form creation to default form type if given purpose has no associated form type

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by everzet** [comment]
Perfect!

**Comment by gquemener** [comment]
Updated https://github.com/KnpLabs/geekweek12/wiki/Form-Manager

**Comment by gquemener** [comment]
I've thought again about the form type creator resolving rules and currently it follows this one:
1. Does PurposeEntityType exist? use it.
2. Does EntityType exist? use it.
3. Does Entity have a parent? Does ParentEntityType exist? use it.
4. Use none (meaning let the default creator handle this entity)

I think it'll be better to follow this one:
1. Does PurposeEntityType exist? use it.
2. Does Entity have a parent? Does PurposeParentEntityType exist? use it.
3. Does EntityType exist? use it.
4. Does Entity have a parent? Does ParentEntityType exist? use it.
5. Use none.

**Comment by everzet** [comment]
@gquemener I think you should remove parent entities support altogether from rule or convention becomes too complex. Convention should be easy and simple to describe. And your "use parent type if no current type available" is easily achievable by creating simply empty type class, that extends parent.

**Comment by everzet** [comment]
We need to preserve balance between complexity of manual implementation and complexity of convention rules.

**Comment by everzet** [comment]
So, rule becomes simple:
1. Does PurposeEntityType exist? use it.
2. Does EntityType exist? use it.
3. Pass resolving task to next creator

**Comment by docteurklein** [comment]
see #16

**Pull request merged**
